name: Actions workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
           pwd
           ls -a
      - name: List Environment Variables
        run: |
          echo $GITHUB_SHA 
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{github.token}}"
          #git clone git@github:$GITHUB_REPOSITORY
          #git checkout $GITHUB_SHA           
      - name: Checkout
        uses: actions/checkout@v1  
      - name: List Files After Checkout
        run: |
           pwd
           ls -a      
      - name: Simple JS Action
        #A unique identifier for the step. You can use the id to reference the step
        id: greet
        #Selects an actionto run as part of a step. An action is a reusable unit of code
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: John
      - name: Log Greeting Time
        run: echo "${{steps.greet.outputs.time }}"    